# Generated by Django 2.2.1 on 2019-08-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('deptid', models.IntegerField(db_column='deptId', primary_key=True, serialize=False)),
                ('deptname', models.CharField(db_column='deptName', max_length=150)),
                ('departshortname', models.CharField(db_column='departShortName', max_length=100)),
                ('departcode', models.CharField(db_column='departCode', max_length=50)),
                ('empid', models.IntegerField(blank=True, db_column='empId', null=True)),
                ('roleid', models.IntegerField(blank=True, db_column='roleId', null=True)),
            ],
            options={
                'db_table': 'admin_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admintable',
            fields=[
                ('adminid', models.AutoField(db_column='adminId', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='updateDate', null=True)),
                ('empid', models.IntegerField(blank=True, db_column='empId', null=True)),
            ],
            options={
                'db_table': 'admintable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('deptid', models.AutoField(db_column='deptId', primary_key=True, serialize=False)),
                ('deptname', models.CharField(blank=True, db_column='deptName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'department_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeeleavebalance',
            fields=[
                ('empleavebalanceid', models.AutoField(db_column='empLeaveBalanceId', primary_key=True, serialize=False)),
                ('leavebalance', models.DecimalField(blank=True, db_column='leaveBalance', decimal_places=2, max_digits=5, null=True)),
                ('quarter', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'employeeleavebalance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('empid', models.AutoField(db_column='empId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, db_column='middleName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=50, null=True)),
                ('emailid', models.CharField(blank=True, db_column='emailId', max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneno', models.CharField(blank=True, db_column='phoneNo', max_length=11, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('updatedate', models.DateField(blank=True, db_column='updateDate', null=True)),
            ],
            options={
                'db_table': 'employee_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaverequestTable',
            fields=[
                ('leaverequestid', models.AutoField(db_column='leaveRequestId', primary_key=True, serialize=False)),
                ('fromdate', models.DateField(blank=True, db_column='fromDate', null=True)),
                ('todate', models.DateField(blank=True, db_column='toDate', null=True)),
                ('noofdayleave', models.DecimalField(blank=True, db_column='noOfDayLeave', decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('applieddate', models.DateField(blank=True, db_column='appliedDate', null=True)),
                ('adminremark', models.TextField(blank=True, db_column='adminRemark', null=True)),
                ('adminremarkdate', models.DateField(blank=True, db_column='adminRemarkDate', null=True)),
            ],
            options={
                'db_table': 'leaverequest_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeavestatusMaster',
            fields=[
                ('leavestatusid', models.AutoField(db_column='leaveStatusId', primary_key=True, serialize=False)),
                ('leavestatus', models.CharField(blank=True, db_column='leaveStatus', max_length=30, null=True)),
            ],
            options={
                'db_table': 'leavestatus_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeavetypesMaster',
            fields=[
                ('leavetypeid', models.AutoField(db_column='leaveTypeId', primary_key=True, serialize=False)),
                ('leavetype', models.CharField(blank=True, db_column='leaveType', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
            ],
            options={
                'db_table': 'leavetypes_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('roleid', models.AutoField(db_column='roleId', primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, db_column='roleName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'role_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblemployees',
            fields=[
                ('empid', models.AutoField(db_column='empId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=150, null=True)),
                ('emailid', models.CharField(blank=True, db_column='emailId', max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=180, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=11, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('updationdate', models.DateTimeField(blank=True, db_column='updationDate', null=True)),
            ],
            options={
                'db_table': 'tblemployees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblleavesenctiondescription',
            fields=[
                ('leavesanctionid', models.AutoField(db_column='leaveSanctionId', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblleavesenctiondescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbluser',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='userName', max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('updationdate', models.DateTimeField(db_column='updationDate')),
            ],
            options={
                'db_table': 'tbluser',
                'managed': False,
            },
        ),
    ]
